---
title: "Wine Ratings - Text Mining"
author: "Luis Noguera"
date: "1/29/2021"
output: html_document
---

# Data Load and Cleaning

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidytext)
library(tidymodels)
library(tidyverse)
library(textrecipes)
library(stringr)

wine_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") 

# Some Cleaning Process
wine_ratings <- wine_ratings %>% 
  extract(title, "year", "(20\\d\\d)", convert = TRUE, remove = FALSE) %>%
  mutate(year = ifelse(year < 1900, NA, year)) %>%
  filter(!is.na(price)) %>%
  select(-X1)  %>%
  mutate(review_id = row_number(),
         description = str_replace_all(description, "[:digit:]", "")) 

wine_ratings 


```

# Data Exploration

```{r}

# Solid normal distribution for points
wine_ratings %>% 
  ggplot(aes(points)) +
  geom_histogram(alpha = 0.8, fill = 'navy blue') +
  theme_minimal() +
  labs(y = NULL,
       x = NULL) +
  scale_y_continuous(labels = comma)


```


```{r}

wine_df <- wine_ratings %>% 
  select(points, description) %>% 
  na.omit() %>% 
  distinct()

word_count_description <- wine_df %>% 
  unnest_tokens(word, description) %>% 
  count(word, sort =  T) %>% 
  anti_join(stop_words) %>% 
  mutate(word = str_to_title(as.factor(word))) %>% 
  rename("Variable" = "word") 
  

```

# Building a Tidy Model 


```{r}

set.seed(415)
wine_split <- initial_split(wine_df)
wine_train <- training(wine_split)
wine_test <- testing(wine_split)


wine_vfolds <- vfold_cv(wine_train, strata = points, v = 5)
wine_vfolds


```

# Data Pre-Processing

```{r}

wine_rec <- recipe(points ~ ., data = wine_train) %>% 
  step_tokenize(description) %>% 
  step_stopwords(description) %>% 
  step_tokenfilter(description, max_tokens = 1e3) %>% 
  step_tfidf(description) 

wine_prep <- wine_rec %>% prep()

wine_juiced <- wine_prep %>%  juice()


```


# Model Fitting 

```{r}

lasso_spec <- linear_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

wine_wf <- workflow() %>%
  add_recipe(wine_rec) %>%
  add_model(lasso_spec)


```


```{r}
lambda_grid <- grid_regular(penalty(range = c(-10, 0)), levels = 50)
```


```{r}

doParallel::registerDoParallel()
set.seed(1234)

lasso_rs <- tune_grid(
  wine_wf,
  resamples = wine_vfolds,
  grid = lambda_grid
)

lasso_rs


```

# Model Evaluation

```{r}

autoplot(lasso_rs) +
  theme_minimal()


show_best(lasso_rs, "rmse")

```


```{r}


best_rmse <- select_best(lasso_rs, "rmse")

final_lasso <- finalize_workflow(wine_wf, best_rmse)
final_lasso


wine_final <- last_fit(final_lasso, wine_split)
collect_metrics(wine_final)

```


```{r}

library(vip)


colors = c("Words Describing Good Wine" = "#2d3252",
          "Words Describing Not So Good Wine" = "#a61a30")

wine_vip <- pull_workflow_fit(wine_final$.workflow[[1]]) %>%
  vi()


Word_importance_table <- wine_vip %>%
  group_by(Sign) %>%
  slice_max(abs(Importance), n = 20) %>%
  ungroup() %>%
  mutate(
    Variable = str_remove(Variable, "tfidf_description_"),
    Importance = abs(Importance),
    Variable = str_to_title(Variable),
    Sign = if_else(Sign == "POS", "Words Describing Good Wine", "Words Describing Not So Good Wine"),
  ) 

words_full_table <-  word_count_description %>% 
  inner_join(Word_importance_table) %>% 
  mutate(Variable = fct_reorder(Variable, Importance)) %>% 
  filter(Variable != "Wine")
  


words_full_table %>% 
  ggplot(aes(Importance, Variable, fill = Sign)) +
  geom_segment(aes(x = 0, xend = Importance, y = Variable, yend = Variable),  show.legend = FALSE) +
  geom_point(aes(size= n, color = Sign), inherit.aes = T, alpha = 0.7, show.legend = F) +
  facet_wrap(~Sign, scales = "free") +
  scale_color_manual(values = colors) +
  labs(y = NULL) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())



library(ggrepel)
?ggrepel()
wine_vip %>%  
  mutate(Variable = str_remove(Variable, "tfidf_description_"),
         Variable = str_to_title(Variable)) %>% 
  inner_join(word_count_description) %>% 
  ggplot(aes(n, Importance, color = Sign, label = Variable)) +
  geom_point(alpha = 0.7, show.legend = F) +
  geom_text_repel() +
  scale_x_log10() +
  theme_minimal() 

?geom_text_repel()
```

# Representing the accuracy of the Lasso model

```{r}


collect_predictions(wine_final) %>%
  ggplot(aes(points, .pred)) +
  geom_abline(lty = 2, color = "gray50", size = 1.2) +
  geom_point(size = 1.5, alpha = 0.3, color = "#88060d") +
  coord_fixed() +
  theme_minimal()


```


